[package]
name = "openlogi-hook"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "OS-level mouse-event hook for Omalogi: evdev grab + uinput re-injection on Linux."

[dependencies]
openlogi-core = { path = "../openlogi-core", version = "0.8.9" }
openlogi-inject = { path = "../openlogi-inject", version = "0.8.9" }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
evdev = { workspace = true }
futures-lite = { workspace = true }
libc = "0.2"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
x11rb = "0.13"
zbus = "5"

[target.'cfg(target_os = "linux")'.dev-dependencies]
ctrlc = "3"

[lints]
workspace = true
